{% set name = "reportlab" %}
{% set version = "3.5.68" %}
{% set sha256 = "efef6a97e3ab49f3f40037dbf9a4166668a17cc6aaba13d5ecbabdf854a9b332" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - freetype
    - pillow >=2.4.0
  run:
    - python
    - freetype
    - pillow >=2.4.0

test:
  imports:
    - reportlab
    - reportlab.graphics
    - reportlab.graphics.barcode
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus

about:
  home: https://www.reportlab.com/opensource/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Open-source engine for creating complex, data-driven PDF documents and custom vector graphics
  dev_url: https://hg.reportlab.com/hg-public/reportlab/
  doc_url: https://www.reportlab.com/dev/docs/
